import React, { createContext, useContext, useState, useCallback, useEffect } from "react";

export type Language = "en" | "zh";

// ============================================================
// FULL TRANSLATION DICTIONARY
// ============================================================
const translations = {
  en: {
    // === NAV ===
    nav_home: "Home",
    nav_cats: "Cats",
    nav_dogs: "Dogs",
    nav_health_topics: "Health Topics",
    nav_breeds: "Breeds",
    nav_monthly_updates: "Monthly Updates",
    nav_content_opportunities: "Content Opportunities",
    nav_reference_library: "Reference Library",
    nav_admin: "Admin",
    nav_sign_in: "Sign In",
    nav_sign_out: "Sign Out",

    // === HOME ===
    home_badge: "Scientific Literature Database",
    home_title_1: "Pet Nutrition",
    home_title_2: "Research Atlas",
    home_subtitle: "A structured research library for feline and canine nutrition, organized by life stage, health scenario, breed relevance, and content opportunity.",
    home_search_placeholder: "Search by topic, breed, life stage, ingredient, or health concern",
    home_search_btn: "Search",
    home_total_papers: "Total Papers",
    home_feline_studies: "Feline Studies",
    home_canine_studies: "Canine Studies",
    home_featured: "Featured",
    home_browse_species: "Browse by Species",
    home_browse_species_sub: "Select a species to explore targeted nutrition research",
    home_browse_cats: "Feline Research",
    home_browse_cats_desc: "Explore nutrition studies, life stage guidance, and breed-specific insights for cats.",
    home_browse_dogs: "Canine Research",
    home_browse_dogs_desc: "Discover evidence-based research on dog nutrition, health topics, and breed needs.",
    home_browse_life_stage: "Browse by Life Stage",
    home_browse_life_stage_sub: "Filter research by developmental phase",
    home_life_junior: "Junior",
    home_life_junior_sub: "Kitten / Puppy",
    home_life_junior_desc: "Growth, development & early immunity",
    home_life_adult: "Adult",
    home_life_adult_sub: "Prime Years",
    home_life_adult_desc: "Maintenance, weight & vitality",
    home_life_senior: "Senior",
    home_life_senior_sub: "Mature & Aging",
    home_life_senior_desc: "Joints, cognition & organ support",
    home_browse_health: "Browse by Health Topic",
    home_browse_health_sub: "15 research categories covering key health scenarios",
    home_view_all_topics: "View All Topics",
    home_featured_papers: "Featured Papers",
    home_featured_sub: "Curated high-evidence studies selected by our research team",
    home_view_library: "View Full Library",
    home_monthly_updates: "Monthly Updates",
    home_monthly_sub: "Latest additions to the research database",
    home_view_all_updates: "View All Updates",
    home_no_papers: "No papers found.",
    home_explore_cats: "Explore Feline Research",
    home_explore_dogs: "Explore Canine Research",

    // === LIBRARY ===
    library_title: "Reference Library",
    library_subtitle: "Full-text searchable database of peer-reviewed nutrition research",
    library_search_placeholder: "Search title, author, keyword...",
    library_filters: "Filters",
    library_clear_all: "Clear All",
    library_species: "Species",
    library_life_stage: "Life Stage",
    library_health_topic: "Health Topic",
    library_breed: "Breed",
    library_study_type: "Study Type",
    library_evidence_level: "Evidence Level",
    library_year: "Year",
    library_all_species: "All Species",
    library_all_stages: "All Life Stages",
    library_all_topics: "All Topics",
    library_all_breeds: "All Breeds",
    library_all_types: "All Study Types",
    library_all_evidence: "All Evidence Levels",
    library_all_years: "All Years",
    library_results: "results",
    library_no_results: "No papers match your current filters.",
    library_clear_filters: "Clear filters",
    library_prev: "Prev",
    library_next: "Next",
    library_page: "Page",
    library_of: "of",
    library_filters_mobile: "Filters",
    library_close_filters: "Close Filters",

    // === PAPER DETAIL ===
    paper_back: "Back to Library",
    paper_authors: "Authors",
    paper_journal: "Journal",
    paper_year: "Year",
    paper_doi: "DOI",
    paper_breeds: "Breeds",
    paper_core_summary: "Core Summary",
    paper_key_findings: "Key Findings",
    paper_practical_relevance: "Practical Relevance",
    paper_limitations: "Study Limitations",
    paper_abstract: "Abstract",
    paper_content_angles: "Brand Content Opportunities",
    paper_harvard_ref: "Harvard Reference",
    paper_copy_ref: "Copy reference",
    paper_copied: "Copied!",
    paper_evidence_strength: "Evidence Strength",
    paper_health_topics: "Health Topics",
    paper_breed_relevance: "Breed Relevance",
    paper_keywords: "Keywords",
    paper_view_original: "View Original Paper",
    paper_related: "Related Papers",
    paper_not_found: "Paper not found.",
    paper_evidence_high_desc: "Well-designed RCT or meta-analysis with consistent results.",
    paper_evidence_medium_desc: "Observational or cohort study with moderate quality evidence.",
    paper_evidence_low_desc: "In vitro, case study, or expert opinion. Interpret with caution.",
    paper_consumer_version: "Consumer Version",
    paper_claim_risk: "Claim Risk Note",
    paper_translate_btn: "Translate to Chinese",
    paper_translating: "Translating...",
    paper_translated_badge: "AI Translated",
    paper_show_original: "Show Original",

    // === SPECIES PAGE ===
    species_cats_title: "Feline Nutrition Research",
    species_dogs_title: "Canine Nutrition Research",
    species_cats_sub: "Evidence-based studies on cat nutrition, health, and breed-specific needs",
    species_dogs_sub: "Evidence-based studies on dog nutrition, health, and breed-specific needs",
    species_life_stages: "Browse by Life Stage",
    species_health_topics: "Key Health Topics",
    species_breeds: "Featured Breeds",
    species_recent_papers: "Recent Papers",
    species_view_all: "View All",
    species_view_library: "View Full Library",
    species_no_topics: "No topics found.",
    species_no_breeds: "No breeds found.",
    species_no_papers: "No papers found.",

    // === HEALTH TOPICS ===
    topics_title: "Health Topics",
    topics_subtitle: "15 research categories covering key nutritional health scenarios for cats and dogs",
    topics_all: "All",
    topics_cats: "Cats",
    topics_dogs: "Dogs",
    topics_papers_count: "papers",
    topics_no_topics: "No topics found.",
    topics_back: "Back to Health Topics",
    topics_related_papers: "Related Papers",
    topics_no_papers: "No papers for this topic yet.",

    // === BREEDS ===
    breeds_title: "Breed Library",
    breeds_subtitle: "Explore breed-specific nutrition research for cats and dogs",
    breeds_all: "All Breeds",
    breeds_cats: "Cats",
    breeds_dogs: "Dogs",
    breeds_no_breeds: "No breeds found.",
    breeds_back: "Back to Breeds",
    breeds_common_issues: "Common Health Issues",
    breeds_nutrition_focus: "Nutrition Focus",
    breeds_related_papers: "Related Research Papers",
    breeds_no_papers: "No papers linked to this breed yet.",
    breeds_papers_count: "papers",

    // === MONTHLY UPDATES ===
    monthly_title: "Monthly Updates",
    monthly_subtitle: "Track new research additions and import activity",
    monthly_new_papers: "New This Month",
    monthly_import_logs: "Import Logs",
    monthly_trigger: "Trigger Import",
    monthly_triggering: "Running...",
    monthly_no_papers: "No new papers this month.",
    monthly_no_logs: "No import logs found.",
    monthly_status_completed: "Completed",
    monthly_status_running: "Running",
    monthly_status_failed: "Failed",
    monthly_found: "Found",
    monthly_imported: "Imported",
    monthly_flagged: "Flagged",
    monthly_triggered_by: "Triggered by",
    monthly_source: "Source",

    // === CONTENT OPPORTUNITIES ===
    content_title: "Content Opportunities",
    content_subtitle: "AI-generated brand content angles derived from peer-reviewed research",
    content_all_formats: "All Formats",
    content_no_angles: "No content angles found.",
    content_consumer: "Consumer",
    content_professional: "Professional",
    content_risk: "Risk Note",
    content_audience: "Audience",
    content_load_more: "Load More",
    content_loading: "Loading...",

    // === ADMIN ===
    admin_title: "Admin CMS",
    admin_subtitle: "Manage literature database, review papers, and trigger AI generation",
    admin_login_required: "Admin Access Required",
    admin_login_desc: "Please sign in with an admin account to access the CMS.",
    admin_sign_in: "Sign In",
    admin_not_admin: "Access Denied",
    admin_not_admin_desc: "Your account does not have admin privileges.",
    admin_stats_total: "Total Papers",
    admin_stats_pending: "Pending Review",
    admin_stats_approved: "Approved",
    admin_stats_featured: "Featured",
    admin_tab_pending: "Pending",
    admin_tab_approved: "Approved",
    admin_tab_rejected: "Rejected",
    admin_search: "Search papers...",
    admin_approve: "Approve",
    admin_reject: "Reject",
    admin_reset: "Reset",
    admin_feature: "Feature",
    admin_unfeature: "Unfeature",
    admin_gen_summary: "AI Summary",
    admin_gen_harvard: "Harvard Ref",
    admin_gen_angles: "Content Angles",
    admin_edit: "Edit",
    admin_save: "Save",
    admin_cancel: "Cancel",
    admin_no_papers: "No papers in this category.",
    admin_generating: "Generating...",
    admin_generated: "Generated!",

    // === COMMON ===
    common_loading: "Loading...",
    common_error: "An error occurred.",
    common_not_found: "Not Found",
    common_back_home: "Back to Home",
    common_feline: "Feline",
    common_canine: "Canine",
    common_both: "Both Species",
    common_high: "High",
    common_medium: "Medium",
    common_low: "Low",
    common_evidence: "Evidence",
    common_featured: "Featured",
    common_read_more: "Read More",
    common_view_paper: "View Paper",
    common_view_papers: "View Papers",
    common_view_all: "View All",
    common_all_topics: "All Topics",
    common_all_breeds: "All Breeds",

    // === SPECIES PAGE EXTRA ===
    species_cat_desc: "Explore peer-reviewed feline nutrition research covering digestive health, skin & coat, urinary tract, kidney support, and breed-specific concerns.",
    species_dog_desc: "Comprehensive canine nutrition literature covering joint mobility, weight management, cognitive aging, heart health, and breed-specific predispositions.",
    species_kitten: "Kitten",
    species_puppy: "Puppy",
    species_prime: "Prime Years",
    species_mature: "Mature & Aging",
    species_junior_desc: "Growth nutrition, immune development, early diet",
    species_adult_desc: "Maintenance, weight, vitality & performance",
    species_senior_desc: "Joint health, cognition, organ support",
    species_browse_life_stage: "Browse by Life Stage",
    species_breed_profiles: "Breed Profiles",

    study_review: "Systematic Review",
    study_rct: "RCT",
    study_observational: "Observational",
    study_in_vitro: "In Vitro",
    study_meta_analysis: "Meta-Analysis",
    study_case_study: "Case Study",
    study_cohort: "Cohort Study",
    study_other: "Other",
    format_xiaohongshu: "小红书 / RED",
    format_ecommerce_detail: "E-commerce Detail",
    format_faq: "FAQ / Q&A",
    format_video_script: "Video Script",
    format_infographic: "Infographic",
    format_brand_education: "Brand Education",
    format_social_post: "Social Post",
    format_scientific_brief: "Scientific Brief",
  },

  zh: {
    // === NAV ===
    nav_home: "首页",
    nav_cats: "猫咪",
    nav_dogs: "犬类",
    nav_health_topics: "健康主题",
    nav_breeds: "品种库",
    nav_monthly_updates: "月度更新",
    nav_content_opportunities: "内容机会",
    nav_reference_library: "文献库",
    nav_admin: "管理后台",
    nav_sign_in: "登录",
    nav_sign_out: "退出",

    // === HOME ===
    home_badge: "学术文献数据库",
    home_title_1: "宠物营养",
    home_title_2: "研究图谱",
    home_subtitle: "面向宠物食品品牌与研究团队的专业文献库，按生命阶段、健康场景、品种相关性与内容机会系统整理。",
    home_search_placeholder: "搜索主题、品种、生命阶段、成分或健康问题",
    home_search_btn: "搜索",
    home_total_papers: "文献总数",
    home_feline_studies: "猫咪研究",
    home_canine_studies: "犬类研究",
    home_featured: "精选",
    home_browse_species: "按物种浏览",
    home_browse_species_sub: "选择物种，探索针对性营养研究",
    home_browse_cats: "猫咪研究",
    home_browse_cats_desc: "探索猫咪营养研究、生命阶段指导与品种专属洞察。",
    home_browse_dogs: "犬类研究",
    home_browse_dogs_desc: "发现基于循证的犬类营养、健康主题与品种需求研究。",
    home_browse_life_stage: "按生命阶段浏览",
    home_browse_life_stage_sub: "按发育阶段筛选研究文献",
    home_life_junior: "幼年期",
    home_life_junior_sub: "幼猫 / 幼犬",
    home_life_junior_desc: "生长发育与早期免疫",
    home_life_adult: "成年期",
    home_life_adult_sub: "黄金年龄",
    home_life_adult_desc: "体重维持与活力管理",
    home_life_senior: "老年期",
    home_life_senior_sub: "成熟与衰老",
    home_life_senior_desc: "关节、认知与器官支持",
    home_browse_health: "按健康主题浏览",
    home_browse_health_sub: "15个研究分类，覆盖核心健康场景",
    home_view_all_topics: "查看全部主题",
    home_featured_papers: "精选文献",
    home_featured_sub: "由研究团队精选的高证据级别研究",
    home_view_library: "查看完整文献库",
    home_monthly_updates: "月度更新",
    home_monthly_sub: "数据库最新收录文献",
    home_view_all_updates: "查看全部更新",
    home_no_papers: "暂无文献。",
    home_explore_cats: "探索猫咪研究",
    home_explore_dogs: "探索犬类研究",

    // === LIBRARY ===
    library_title: "参考文献库",
    library_subtitle: "同行评审营养研究全文检索数据库",
    library_search_placeholder: "搜索标题、作者、关键词...",
    library_filters: "筛选条件",
    library_clear_all: "清除全部",
    library_species: "物种",
    library_life_stage: "生命阶段",
    library_health_topic: "健康主题",
    library_breed: "品种",
    library_study_type: "研究类型",
    library_evidence_level: "证据强度",
    library_year: "发表年份",
    library_all_species: "全部物种",
    library_all_stages: "全部阶段",
    library_all_topics: "全部主题",
    library_all_breeds: "全部品种",
    library_all_types: "全部类型",
    library_all_evidence: "全部证据级别",
    library_all_years: "全部年份",
    library_results: "条结果",
    library_no_results: "没有符合当前筛选条件的文献。",
    library_clear_filters: "清除筛选",
    library_prev: "上一页",
    library_next: "下一页",
    library_page: "第",
    library_of: "共",
    library_filters_mobile: "筛选",
    library_close_filters: "关闭筛选",

    // === PAPER DETAIL ===
    paper_back: "返回文献库",
    paper_authors: "作者",
    paper_journal: "期刊",
    paper_year: "年份",
    paper_doi: "DOI",
    paper_breeds: "相关品种",
    paper_core_summary: "核心摘要",
    paper_key_findings: "主要发现",
    paper_practical_relevance: "实践意义",
    paper_limitations: "研究局限性",
    paper_abstract: "摘要",
    paper_content_angles: "品牌内容创作方向",
    paper_harvard_ref: "Harvard 引用格式",
    paper_copy_ref: "复制引用",
    paper_copied: "已复制！",
    paper_evidence_strength: "证据强度",
    paper_health_topics: "健康主题",
    paper_breed_relevance: "品种相关性",
    paper_keywords: "关键词",
    paper_view_original: "查看原文",
    paper_related: "相关文献",
    paper_not_found: "未找到该文献。",
    paper_evidence_high_desc: "设计严谨的随机对照试验或荟萃分析，结果一致性高。",
    paper_evidence_medium_desc: "观察性研究或队列研究，证据质量中等。",
    paper_evidence_low_desc: "体外实验、案例研究或专家意见，解读时需谨慎。",
    paper_consumer_version: "消费者版本",
    paper_claim_risk: "声称风险提示",
    paper_translate_btn: "翻译为中文",
    paper_translating: "正在翻译...",
    paper_translated_badge: "AI 翻译",
    paper_show_original: "显示原文",

    // === SPECIES PAGE ===
    species_cats_title: "猫咪营养研究",
    species_dogs_title: "犬类营养研究",
    species_cats_sub: "基于循证的猫咪营养、健康与品种专属需求研究",
    species_dogs_sub: "基于循证的犬类营养、健康与品种专属需求研究",
    species_life_stages: "按生命阶段浏览",
    species_health_topics: "核心健康主题",
    species_breeds: "精选品种",
    species_recent_papers: "最新文献",
    species_view_all: "查看全部",
    species_view_library: "查看完整文献库",
    species_no_topics: "暂无主题。",
    species_no_breeds: "暂无品种。",
    species_no_papers: "暂无文献。",

    // === HEALTH TOPICS ===
    topics_title: "健康主题",
    topics_subtitle: "15个研究分类，覆盖猫咪与犬类核心营养健康场景",
    topics_all: "全部",
    topics_cats: "猫咪",
    topics_dogs: "犬类",
    topics_papers_count: "篇文献",
    topics_no_topics: "暂无主题。",
    topics_back: "返回健康主题",
    topics_related_papers: "相关文献",
    topics_no_papers: "该主题暂无文献。",

    // === BREEDS ===
    breeds_title: "品种库",
    breeds_subtitle: "探索猫咪与犬类品种专属营养研究",
    breeds_all: "全部品种",
    breeds_cats: "猫咪",
    breeds_dogs: "犬类",
    breeds_no_breeds: "暂无品种。",
    breeds_back: "返回品种库",
    breeds_common_issues: "常见健康问题",
    breeds_nutrition_focus: "营养重点",
    breeds_related_papers: "相关研究文献",
    breeds_no_papers: "该品种暂无关联文献。",
    breeds_papers_count: "篇文献",

    // === MONTHLY UPDATES ===
    monthly_title: "月度更新",
    monthly_subtitle: "追踪最新研究收录与导入动态",
    monthly_new_papers: "本月新增",
    monthly_import_logs: "导入日志",
    monthly_trigger: "触发导入",
    monthly_triggering: "运行中...",
    monthly_no_papers: "本月暂无新增文献。",
    monthly_no_logs: "暂无导入日志。",
    monthly_status_completed: "已完成",
    monthly_status_running: "运行中",
    monthly_status_failed: "失败",
    monthly_found: "发现",
    monthly_imported: "已导入",
    monthly_flagged: "已标记",
    monthly_triggered_by: "触发者",
    monthly_source: "来源",

    // === CONTENT OPPORTUNITIES ===
    content_title: "内容机会",
    content_subtitle: "基于同行评审研究，AI 生成的品牌内容创作方向",
    content_all_formats: "全部格式",
    content_no_angles: "暂无内容方向。",
    content_consumer: "消费者版",
    content_professional: "专业版",
    content_risk: "风险提示",
    content_audience: "目标受众",
    content_load_more: "加载更多",
    content_loading: "加载中...",

    // === ADMIN ===
    admin_title: "管理后台",
    admin_subtitle: "管理文献数据库、审核文献并触发 AI 生成",
    admin_login_required: "需要管理员权限",
    admin_login_desc: "请使用管理员账号登录以访问 CMS。",
    admin_sign_in: "登录",
    admin_not_admin: "访问被拒绝",
    admin_not_admin_desc: "您的账号没有管理员权限。",
    admin_stats_total: "文献总数",
    admin_stats_pending: "待审核",
    admin_stats_approved: "已通过",
    admin_stats_featured: "精选",
    admin_tab_pending: "待审核",
    admin_tab_approved: "已通过",
    admin_tab_rejected: "已拒绝",
    admin_search: "搜索文献...",
    admin_approve: "通过",
    admin_reject: "拒绝",
    admin_reset: "重置",
    admin_feature: "设为精选",
    admin_unfeature: "取消精选",
    admin_gen_summary: "AI 摘要",
    admin_gen_harvard: "Harvard 引用",
    admin_gen_angles: "内容方向",
    admin_edit: "编辑",
    admin_save: "保存",
    admin_cancel: "取消",
    admin_no_papers: "该分类暂无文献。",
    admin_generating: "生成中...",
    admin_generated: "已生成！",

    // === COMMON ===
    common_loading: "加载中...",
    common_error: "发生错误。",
    common_not_found: "未找到",
    common_back_home: "返回首页",
    common_feline: "猫咪",
    common_canine: "犬类",
    common_both: "猫犬通用",
    common_high: "高",
    common_medium: "中",
    common_low: "低",
    common_evidence: "证据",
    common_featured: "精选",
    common_read_more: "阅读更多",
    common_view_paper: "查看文献",
    common_view_papers: "查看文献",
    common_view_all: "查看全部",
    common_all_topics: "全部主题",
    common_all_breeds: "全部品种",

    // === SPECIES PAGE EXTRA ===
    species_cat_desc: "探索猫咪营养同行评审研究，涵盖消化健康、皮肤与毛发、泌尿系统、肾脏支持及品种专属问题。",
    species_dog_desc: "全面的犬类营养文献，涵盖关节活动、体重管理、认知衰老、心脏健康及品种专属倾向。",
    species_kitten: "幼猫",
    species_puppy: "幼犬",
    species_prime: "黄金年龄",
    species_mature: "成熟与衰老",
    species_junior_desc: "生长营养、免疫发育与早期饮食",
    species_adult_desc: "体重维持、活力与体能管理",
    species_senior_desc: "关节健康、认知与器官支持",
    species_browse_life_stage: "按生命阶段浏览",
    species_breed_profiles: "品种档案",

    study_review: "系统综述",
    study_rct: "随机对照试验",
    study_observational: "观察性研究",
    study_in_vitro: "体外实验",
    study_meta_analysis: "荟萃分析",
    study_case_study: "案例研究",
    study_cohort: "队列研究",
    study_other: "其他",
    format_xiaohongshu: "小红书",
    format_ecommerce_detail: "电商详情页",
    format_faq: "常见问题",
    format_video_script: "视频脚本",
    format_infographic: "信息图",
    format_brand_education: "品牌科普",
    format_social_post: "社交媒体",
    format_scientific_brief: "科学简报",
  },
} as const;

export type TranslationKey = keyof typeof translations.en;

// ============================================================
// CONTEXT
// ============================================================
interface LanguageContextValue {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: TranslationKey) => string;
  isZh: boolean;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Language>(() => {
    try {
      const stored = localStorage.getItem("pnra_lang");
      if (stored === "zh" || stored === "en") return stored;
    } catch {}
    return "en";
  });

  const setLang = useCallback((newLang: Language) => {
    setLangState(newLang);
    try { localStorage.setItem("pnra_lang", newLang); } catch {}
  }, []);

  const t = useCallback((key: TranslationKey): string => {
    return (translations[lang] as Record<string, string>)[key]
      ?? (translations.en as Record<string, string>)[key]
      ?? key;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, isZh: lang === "zh" }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
